# Project language
language: php

# Allows use container-based infrastructure
sudo: false

php:
  - 5.6

# Start mysql service
services:
  - docker

# Update composer
before-install:
  - composer self-update
  - docker version
  - docker-compose version
  - docker-compose build
  - docker-compose up -d

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - . $HOME/.nvm/nvm.sh && nvm install stable && nvm use stable
  - npm install -g newman
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - docker-compose exec php php bin/console doctrine:database:create
  - docker-compose exec php php bin/console doctrine:schema:create
  - docker-compose exec php php bin/console doctrine:fixtures:load -n

# Run script
script:
  - ./run_tests.sh
