version: "3"

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password

  php:
    build: .docker/php
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      - SYMFONY_ENV=dev
    links:
      - db:db

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - db:db

  elk:
    image: willdurand/elk
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
      - .docker/elk/logstash:/etc/logstash
      - .docker/elk/logstash/patterns:/opt/logstash/patterns
