gsapi:
    type: rest
    resource: "@GSApiBundle/Resources/config/routing.yml"
    prefix:   /api
    schemes: ['%httpProtocol%']

gs_e_transaction:
    resource: "@GSETransactionBundle/Resources/config/routing.yml"
    prefix:   /etrans
    schemes: ['%httpProtocol%']
