# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext

        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_MEMBER:        ROLE_USER
        ROLE_PRIVILEGED:    ROLE_USER
        ROLE_SECRETARY:     ROLE_PRIVILEGED
        ROLE_TREASURER:     ROLE_PRIVILEGED
        ROLE_TOPIC_MANAGER: ROLE_PRIVILEGED
        ROLE_ORGANIZER:     ROLE_TOPIC_MANAGER
        ROLE_ADMIN:         [ROLE_TREASURER, ROLE_SECRETARY, ROLE_ORGANIZER]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/api/auth
            provider: fos_userbundle
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/auth
                username_parameter:       login
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        reset_password:
            pattern:   ^/api/resetting
            anonymous: true

        main:
            pattern: ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
