
api_login_check:
    path: /auth

logout:
    path: /logout

account:
    type:     rest
    resource: GS\ApiBundle\Controller\AccountController

venue:
    type:     rest
    resource: GS\ApiBundle\Controller\VenueController

year:
    type:     rest
    resource: GS\ApiBundle\Controller\YearController

activity:
    type:     rest
    resource: GS\ApiBundle\Controller\ActivityController

category:
    type:     rest
    resource: GS\ApiBundle\Controller\CategoryController

discount:
    type:     rest
    resource: GS\ApiBundle\Controller\DiscountController

topic:
    type:     rest
    resource: GS\ApiBundle\Controller\TopicController

registration:
    type:     rest
    resource: GS\ApiBundle\Controller\RegistrationController

payment:
    type:     rest
    resource: GS\ApiBundle\Controller\PaymentController

paypal:
    resource: GS\ApiBundle\Controller\PaypalController
    type:     annotation

user:
    type:     rest
    resource: GS\ApiBundle\Controller\UserController
