services:
#    gsapi.example:
#        class: GS\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gsapi.ipn.listener:
        class: GS\ApiBundle\EventListener\IpnListener
        arguments:
            - '%kernel.root_dir%'
            - '@filesystem'
            - '@doctrine.orm.entity_manager'
            - '@gsapi.payment.service'
        tags:
            - { name: kernel.event_listener, event: gse_transaction.ipn.received, method: onIpnReceived }

    gsapi.user.listener:
        class: GS\ApiBundle\EventListener\UserListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    gsapi.form_generator:
        class: GS\ApiBundle\Services\FormGeneratorService
        arguments: [ '@router', '@form.factory', '@doctrine.orm.entity_manager' ]

    gsapi.account_balance:
        class: GS\ApiBundle\Services\AccountBalanceService
        arguments: [ '@doctrine.orm.entity_manager' ]

    gsapi.user.repository:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - GS\StructureBundle\Entity\User

    gsapi.event.jwt_created_listener:
        class: GS\ApiBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    gsapi.event.jwt_decoded_listener:
        class: GS\ApiBundle\EventListener\JWTDecodedListener
        arguments: [ '@gsapi.user.repository' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    gsapi.event.table_prefix_subscriber:
        class: GS\ApiBundle\EventSubscriber\TablePrefixSubscriber
        public: false
        arguments: ['']
        tags:
            - { name: doctrine.event_subscriber }

    gsapi.user.membership:
        class: GS\ApiBundle\Services\MembershipService
        arguments: [ '@doctrine.orm.entity_manager' ]

    gsapi.registration.service:
        class: GS\ApiBundle\Services\RegistrationService
        arguments: [ '@doctrine.orm.entity_manager', '@mailer', '@lexik_mailer.message_factory' ]

    gsapi.payment.service:
        class: GS\ApiBundle\Services\PaymentService
        arguments: [ '@mailer', '@lexik_mailer.message_factory' ]
