services:
#    gsapi.example:
#        class: GS\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gsapi.form.user.registration:
            class: GS\ApiBundle\Form\Type\UserRegistrationType
            tags:
                - { name: form.type, alias: gsapi_user_registration }

    gsapi.form.user.profile:
            class: GS\ApiBundle\Form\Type\UserProfileType
            tags:
                - { name: form.type, alias: gsapi_user_profile }

    jms_serializer.handler.relation:
        class: GS\ApiBundle\Serializer\RelationsHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: jms_serializer.handler, type: Relation, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: Relation, direction: deserialization, format: json, method: deserializeRelation}
            - { name: jms_serializer.handler, type: Relation<?>, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: Relation<?>, direction: deserialization, format: json, method: deserializeRelation}

    gsapi.user.registration:
        class: GS\ApiBundle\EventListener\UserRegistrationListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }

    gsapi.account_balance:
        class: GS\ApiBundle\Services\AccountBalanceService
        arguments: [ '@doctrine.orm.entity_manager' ]

    gsapi.account_voter:
        class: GS\ApiBundle\Security\AccountVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.venue_voter:
        class: GS\ApiBundle\Security\VenueVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.registration_voter:
        class: GS\ApiBundle\Security\RegistrationVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.year_voter:
        class: GS\ApiBundle\Security\YearVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.activity_voter:
        class: GS\ApiBundle\Security\ActivityVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.topic_voter:
        class: GS\ApiBundle\Security\TopicVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.category_discount_voter:
        class: GS\ApiBundle\Security\CategoryDiscountVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.payment_voter:
        class: GS\ApiBundle\Security\PaymentVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.invoice_voter:
        class: GS\ApiBundle\Security\InvoiceVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.user.repository:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - GS\ApiBundle\Entity\User

    gsapi.event.table_prefix_subscriber:
        class: GS\ApiBundle\EventSubscriber\TablePrefixSubscriber
        public: false
        arguments: ['']
        tags:
            - { name: doctrine.event_subscriber }

    gsapi.user.membership:
        class: GS\ApiBundle\Services\MembershipService
        arguments: [ '@doctrine.orm.entity_manager' ]

#    gsapi.registration.service:
#        class: GS\ApiBundle\Services\RegistrationService
#        arguments: [ '@doctrine.orm.entity_manager' ]
