services:
#    gsapi.example:
#        class: GS\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    jms_serializer.handler.relation:
        class: GS\ApiBundle\Serializer\RelationsHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: jms_serializer.handler, type: Relation, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: Relation, direction: deserialization, format: json, method: deserializeRelation}
            - { name: jms_serializer.handler, type: Relation<?>, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: Relation<?>, direction: deserialization, format: json, method: deserializeRelation}

    gsapi.form_generator:
        class: GS\ApiBundle\Services\FormGeneratorService
        arguments: [ '@router', '@form.factory' ]
    
    gsapi.account_balance:
        class: GS\ApiBundle\Services\AccountBalanceService
        arguments: [ '@doctrine.orm.entity_manager' ]
    
    gsapi.account_voter:
        class: GS\ApiBundle\Security\AccountVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.venue_voter:
        class: GS\ApiBundle\Security\VenueVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.registration_voter:
        class: GS\ApiBundle\Security\RegistrationVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.year_voter:
        class: GS\ApiBundle\Security\YearVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.activity_voter:
        class: GS\ApiBundle\Security\ActivityVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.topic_voter:
        class: GS\ApiBundle\Security\TopicVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.category_discount_voter:
        class: GS\ApiBundle\Security\CategoryDiscountVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    gsapi.payment_voter:
        class: GS\ApiBundle\Security\PaymentVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
